### PR TITLE
Update erlang package

### PR DESCRIPTION
**Pull request by cf-london**
This PR updates the version of erlang to 20.3.8.2

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@cf-london Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal-cf/cf-rabbitmq-release&pullRequestId=97)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=pivotal-cf/cf-rabbitmq-release&pullRequestId=97) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@cf-london Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal-cf/cf-rabbitmq-release&pullRequestId=97)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=pivotal-cf/cf-rabbitmq-release&pullRequestId=97) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@cf-london Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal-cf/cf-rabbitmq-release&pullRequestId=97)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=pivotal-cf/cf-rabbitmq-release&pullRequestId=97) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by flangewad** [comment]
Don't merge this one - we tried this update already and it broke https://pcf-rabbitmq.ci.cf-app.com/teams/main/pipelines/cf-rabbitmq-release/jobs/create-bosh-release/builds/133

**Pull request merged**
