### PR TITLE
Added Openstack stuff

### PR DESCRIPTION
**Pull request by axelaris**
Hi guys,
I've added support to Openstack backend.
Could you please take a look.

### CODE REVIEW

**Comment by axelaris** [comment]
anyone?

**Comment by davidhiston** [comment]
Hi @axelaris.  Sorry for the delay, I am reviewing your request and will get back to you. 

Thanks, 

Dave

**Comment by davidhiston** [comment]
We have already accepted a similar pull request.  Please review.

**Comment by axelaris** [comment]
@davidhiston, seriously? "Similar pull request" which came 6 months later?

**Pull request closed without merging**
