### PR TITLE
Accomodate pcfdev

### PR DESCRIPTION
**Pull request by mdelillo**
- Increase monit timeout for slower boxes
- Rename rabbitmq packages to avoid conflicts

We previously opened https://github.com/pivotal-cf/cf-rabbitmq-release/pull/19 a few months ago, so we rebased it on top of master and are opening a new one.

### CODE REVIEW

**Comment by sclevine** [comment]
@davidhiston will you take this PR if we rebase again? We've been trying to get these changes in for a very long time.

**Comment by sclevine** [comment]
@davidhiston Any update on this?

**Comment by davidhiston** [comment]
Hi @sclevine.  We have been working on a number of internal updates and merging would have added to much churn at the time.  We are now through that and will prioritsie in our backlog. Thanks.

**Comment by sclevine** [comment]
Awesome, thanks! Let us know if/when rebasing would help.

**Comment by svett** [comment]
Because this has diverged from master, we had to manually merge it. While this is going through our pipeline, we want to make the following changes:

1. Make naming consistent for **rabbitmq-syslog-aggregator** package
1. Rather than namespacing the Golang package, we're thinking to add the version, e.g. **golang-v1.6.2**
1. Rather than using a 10 minute timeout, we want to remove the rabbitmq-broker timeout all together

**Comment by svett** [comment]
https://github.com/pivotal-cf/cf-rabbitmq-release/commit/04ab6a8a92a1bbc680e73c2628ee89442e7658e3

**Pull request closed without merging**
