### PR TITLE
added support for configurable uuid

### PR DESCRIPTION
**Pull request by longnguyen11288**

### CODE REVIEW

**Comment by longnguyen11288** [comment]
fixes https://github.com/pivotal-cf/cf-rabbitmq-release/issues/9

**Comment by longnguyen11288** [comment]
bump

**Comment by benlaplanche** [comment]
@longnguyen11288 have you signed the Pivotal CLA?

**Comment by longnguyen11288** [comment]
@benlaplanche I have

**Comment by longnguyen11288** [comment]
bump

**Comment by williammartin** [comment]
Hello longnguyen11288, I have accepted this change in commit: https://github.com/pivotal-cf/cf-rabbitmq-release/commit/fe18845d610805733b5e2e3355e6a2d8c742095d and fixed a failing broker unit test in https://github.com/pivotal-cf/cf-rabbitmq-release/commit/413ac6a437ba44e6427bc775920c455bf93c3806 which you may want.

This change should be available in the cf-rabbitmq-170 release.

Thank you for the pull request.

**Pull request closed without merging**
